Adding double splat for Ruby 3.0 support
Splat method no longer passing keyword argument as keyword argument,
resulting in us getting ArgumentError:

    ArgumentError: wrong number of arguments (given 3, expected 1..2)
    $GEM_HOME/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:199:in `execute'
    $GEM_HOME/active_record_mysql_xverify-0.2.2/lib/active_record_mysql_xverify/error_handler.rb:6:in `execute'
    $GEM_HOME/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:207:in `execute_and_free'
    $GEM_HOME/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:817:in `column_definitions'
    $GEM_HOME/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
    $GEM_HOME/activerecord-7.0.2.3/lib/active_record/connection_adapters/schema_cache.rb:117:in `block in columns'
    $GEM_HOME/activerecord-7.0.2.3/lib/active_record/connection_adapters/schema_cache.rb:116:in `fetch'